### PR TITLE
Add slider component

### PR DESCRIPTION
**Pull request by awesomebob**

### CODE REVIEW

**Comment by dustinsoftware** [comment]
I'm seeing inconsistent focus states on Firefox

**Comment by awesomebob** [comment]
@dustinsoftware I've added basic keyboard (arrow key) support and tested it in both Chrome and Firefox. The focus states now look consistent to me, do you still see any differences?

**Comment by dustinsoftware** [comment]
I’m still seeing minor selection bugs on iOS. Let’s merge as is and send another PR to resolve those issues.

**Comment by dustinsoftware** [comment]
0cbab524-7dc5-4dc3-9c14-9ba18867eb4c

**Pull request merged**
