### PR TITLE
React select bump

### PR DESCRIPTION
**Pull request by bryankenote**
updated imports according to this guide: https://github.com/JedWatson/react-select/issues/3585

### CODE REVIEW

**Comment by RobertBolender** [comment]
The update from Emotion 9 to 10 makes me nervous, we'll need to make sure this builds nicely in FLCOM with SSR before merging this.
@bryankenote Was there a time-sensitive need for this update on your end?

**Comment by bryankenote** [comment]
No rush. Better to take time to make sure nothing else breaks.

**Comment by RobertBolender** [comment]
Understood. Thanks for putting the PR together, I'll test it out within FLCOM soonish.

**Comment by RobertBolender** [comment]
Good news, I was able to get [Emotion v10 working nicely in FLCOM](https://git.faithlife.dev/Logos/Faithlife/pull/4393), unblocking this version update. I've cherry-picked your commit onto the v6 PR (https://github.com/Faithlife/styled-ui/pull/413) and will merge it when we're ready to ship v6 (very soon).

**Pull request closed without merging**
